
-- Enable PostGIS extension for location data
CREATE EXTENSION IF NOT EXISTS postgis;

-- Enable UUID extension for generating UUIDs
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- PROFILES (Users)
CREATE TABLE public.profiles (
    id UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
    email TEXT,
    nickname TEXT,
    profile_image TEXT,
    agreements JSONB DEFAULT '{}'::jsonb,
    role TEXT DEFAULT 'user' CHECK (role IN ('user', 'admin')),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- RLS for profiles
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public profiles are viewable by everyone." ON public.profiles
    FOR SELECT USING (true);

CREATE POLICY "Users can insert their own profile." ON public.profiles
    FOR INSERT WITH CHECK (auth.uid() = id);

CREATE POLICY "Users can update own profile." ON public.profiles
    FOR UPDATE USING (auth.uid() = id);

-- Trigger to create profile on signup
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, email, nickname, profile_image)
  VALUES (new.id, new.email, new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'avatar_url');
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();


-- STORES (Restaurants)
CREATE TABLE public.stores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    category TEXT NOT NULL,
    address TEXT NOT NULL,
    location GEOGRAPHY(POINT, 4326), -- PostGIS Geography for accurate distance calculation
    image_url TEXT,
    status TEXT DEFAULT 'NORMAL' CHECK (status IN ('NORMAL', 'CHALLENGE', 'PENDING', 'REJECTED')),
    price_range TEXT CHECK (price_range IN ('WON_1', 'WON_2', 'WON_3')),
    rating NUMERIC(3, 2) DEFAULT 0,
    review_count INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX stores_location_idx ON public.stores USING GIST (location);

-- RLS for stores
ALTER TABLE public.stores ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Stores are viewable by everyone." ON public.stores
    FOR SELECT USING (true);

CREATE POLICY "Only admins can insert/update stores." ON public.stores
    FOR ALL USING (auth.uid() IN (SELECT id FROM public.profiles WHERE role = 'admin'));


-- MENUS
CREATE TABLE public.menus (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id BIGINT REFERENCES public.stores(id) ON DELETE CASCADE NOT NULL,
    name TEXT NOT NULL,
    price INTEGER NOT NULL,
    image_url TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- RLS for menus
ALTER TABLE public.menus ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Menus are viewable by everyone." ON public.menus
    FOR SELECT USING (true);


-- BUSINESS HOURS
CREATE TABLE public.business_hours (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id BIGINT REFERENCES public.stores(id) ON DELETE CASCADE NOT NULL,
    day_of_week TEXT NOT NULL CHECK (day_of_week IN ('MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY')),
    open_time TIME,
    close_time TIME,
    break_start TIME,
    break_end TIME,
    last_order TIME,
    is_closed BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- RLS for business_hours
ALTER TABLE public.business_hours ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Business hours are viewable by everyone." ON public.business_hours
    FOR SELECT USING (true);


-- FACILITIES
CREATE TABLE public.facilities (
    store_id BIGINT REFERENCES public.stores(id) ON DELETE CASCADE PRIMARY KEY,
    parking BOOLEAN DEFAULT FALSE,
    takeout BOOLEAN DEFAULT FALSE,
    delivery BOOLEAN DEFAULT FALSE,
    indoor_restroom BOOLEAN DEFAULT FALSE,
    outdoor_restroom BOOLEAN DEFAULT FALSE,
    group_seating BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- RLS for facilities
ALTER TABLE public.facilities ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Facilities are viewable by everyone." ON public.facilities
    FOR SELECT USING (true);


-- STORE LIKES
CREATE TABLE public.store_likes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id BIGINT REFERENCES public.stores(id) ON DELETE CASCADE NOT NULL,
    user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(store_id, user_id)
);

-- RLS for store_likes
ALTER TABLE public.store_likes ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Store likes are viewable by everyone." ON public.store_likes
    FOR SELECT USING (true);

CREATE POLICY "Users can create their own likes." ON public.store_likes
    FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can delete their own likes." ON public.store_likes
    FOR DELETE USING (auth.uid() = user_id);


-- STORE BOOKMARKS
CREATE TABLE public.store_bookmarks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id BIGINT REFERENCES public.stores(id) ON DELETE CASCADE NOT NULL,
    user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(store_id, user_id)
);

-- RLS for store_bookmarks
ALTER TABLE public.store_bookmarks ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Store bookmarks are viewable by everyone." ON public.store_bookmarks
    FOR SELECT USING (true);

CREATE POLICY "Users can create their own bookmarks." ON public.store_bookmarks
    FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can delete their own bookmarks." ON public.store_bookmarks
    FOR DELETE USING (auth.uid() = user_id);


-- CHALLENGE APPLICATIONS (Pending Stores)
-- Instead of a separate table structure, we can reuse `stores` with status='PENDING'
-- But since it has a "comment" and "applicant_id", we might want a separate table linking to the store ID.
-- Or just add these columns to `stores` and make them nullable.
-- Let's create a separate table for the application metadata that links to the store.

CREATE TABLE public.challenge_applications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    applicant_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
    store_id BIGINT REFERENCES public.stores(id) ON DELETE CASCADE, -- The store created from this application
    comment TEXT,
    status TEXT DEFAULT 'PENDING' CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED')),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- RLS for challenge_applications
ALTER TABLE public.challenge_applications ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view their own applications." ON public.challenge_applications
    FOR SELECT USING (auth.uid() = applicant_id);

CREATE POLICY "Users can create applications." ON public.challenge_applications
    FOR INSERT WITH CHECK (auth.uid() = applicant_id);
